name: Cambricon Device Plugin CI

on:
  pull_request:
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-16.04
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: lint
      run: test -z `go fmt ./...`

    - name: vet
      run: go vet ./...

    - name: Build
      run: go build -v .

  test:
    name: Test device plugin on self-hosted runner
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v2

    - name: Test Device plugin
      run: bash ./test/deploy-test-device-plugin.sh
